spring.application.name=mail-service

server.port=6666

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sontakkerohan751@gmail.com
spring.mail.password=zgrw lfsi injv llgd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com